# Generated by Django 5.1.4 on 2025-01-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='include_vat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
