# Generated by Django 5.1.4 on 2025-01-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_include_vat_transaction_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('הכנסה', 'הכנסה'), ('הוצאה', 'הוצאה')], default='הכנסה', max_length=20),
        ),
    ]
