# Generated by Django 5.1.4 on 2025-01-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_date_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
